export const CURRENCY_REQUESTING = 'CURRENCY_REQUESTING';
export const CURRENCY_SUCCESS = 'CURRENCY_SUCCESS';
export const CURRENCY_ERROR = 'CURRENCY_ERROR';

export const CURRENCY_RESET_STATES = 'CURRENCY_RESET_STATES';