export const CURRENCY_REQUESTING: string = 'CURRENCY_REQUESTING';
export const CURRENCY_SUCCESS: string = 'CURRENCY_SUCCESS';
export const CURRENCY_ERROR: string = 'CURRENCY_ERROR';

export const CURRENCY_DETAIL_REQUESTING: string = 'CURRENCY_DETAIL_REQUESTING';
export const CURRENCY_DETAIL_SUCCESS: string = 'CURRENCY_DETAIL_SUCCESS';
export const CURRENCY_DETAIL_ERROR: string = 'CURRENCY_DETAIL_ERROR';

export const CURRENCY_RESET_STATES: string = 'CURRENCY_RESET_STATES';